# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/arush/ece385_final_project/ece385_final_project.srcs/sources_1/ip/mario_rom/mario_rom.xci
# IP: The module: 'mario_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arush/ece385_final_project/ece385_final_project.gen/sources_1/ip/mario_rom/mario_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mario_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/arush/ece385_final_project/ece385_final_project.srcs/sources_1/ip/mario_rom/mario_rom.xci
# IP: The module: 'mario_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arush/ece385_final_project/ece385_final_project.gen/sources_1/ip/mario_rom/mario_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mario_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
